exclude: '^(vendor/)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
        name: Check merge confict
      - id: trailing-whitespace
        name: Check trailing whitespace
      - id: end-of-file-fixer
        name: Check end of file only one newline
      - id: check-added-large-files
        name: Check large files
      - id: check-yaml
        name: Check .yaml .yml .eyaml .eyml
        files: (\.yaml|\.yml|\.eyaml|\.eyml)$
        args: ["--allow-multiple-documents"]
  - repo: https://github.com/dnephin/pre-commit-golang.git
    rev: v0.5.1
    hooks:
      - id: go-fmt
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        # language: golang
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
