---
SlackToken:
RequestDelay: 1200
ChannelTypes:
  # - "public_channel"
  # - "private_channel"
  # - "mpim"
  # - "im"
ExportBasePath: "./export"
SplitMessages: false
ArchiveData: true
DownloadFiles: true
IncludeChannel:
  # - "general"
  # - "random"
  # - "@someone"
  # - "mpdm-user1--user2--user3-1"
